//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelephoneContact
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Comments { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual Person Person { get; set; }
    }
}
